calculator: main.o addition.o divission.o print_result.o
	g++ main.o addition.o divission.o print_result.o -o calculator

main.o: main.cpp
		g++ -c main.cpp

addition.o: addition.cpp
		g++ -c addition.cpp

divission.o: divission.cpp
		g++ -c divission.cpp

print_result.o: print_result.cpp
		g++ -c print_result.cpp